export const QueryKeys = {
  GET_COURT_LIST: "GET_COURT_LIST",
  GET_COURT_TYPE_LIST: "GET_COURT_TYPE_LIST",
  GET_RESERVATION: "GET_RESERVATION",
  GET_USER_LIST: "GET_USER_LIST",
  GET_AUTHENTICATED: "authenticated_user",
  GET_STATISTIC_BOOKING_HOUR: "GET_STATISTIC_BOOKING_HOUR",
  GET_STATISTIC_NEW_USER: "GET_STATISTIC_NEW_USER",
  GET_STATISTIC_REVENUE: "GET_STATISTIC_REVENUE",
  GET_STATISTIC_REVENUE_BY_MONTH: "GET_STATISTIC_REVENUE_BY_MONTH",
};
